[project]
name = "mkdocs-template"
version = "0.1.0"
description = "Template for documentation projects using mkdocs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
]
